EO2-WAVY/WavyBackend

.gitignore, package-lock.json, package.json, src/app.module.ts, src/common/common.module.ts, src/common/entities/code.entity.ts, src/common/entities/core.entity.ts, src/common/enums/code.enum.ts, src/members/entities/members.entity.ts
TypeORM 환경 설정 및 core, code, member 엔티티 생성
#3
=> [#3] 데이터베이스 셋업

package-lock.json, src/app.module.ts, src/common/entities/code.entity.ts, src/common/entities/core.entity.ts, src/common/enums/code.enum.ts, src/members/entities/members.entity.ts, src/practices/entities/practice.entity.ts, src/ref-videoes/entities/ref-video.entity.ts
=> [#3] 데이터 베이스 세팅

src/analyses/entities/analyses.entity.ts, src/app.module.ts, src/common/enums/code.enum.ts, src/members-ref-videoes/entities/members-ref-videoes.entity.ts, src/members/entities/members.entity.ts, src/ref-videoes/entities/ref-video.entity.ts
- Analysis 엔티티 추가
- MemberRefVido 엔티티 추가
#3
=> [#3] 데이터베이스 ORM 셋업

src/app.module.ts, src/ref-videoes/entities/ref-video.entity.ts, src/ref-videoes/entities/tag.entity.ts
=> [#15] Tag 엔티티 추가

package-lock.json, package.json, src/common/dtos/pagination.dto.ts, src/ref-videos/dtos/ref-videos.dto.ts, src/ref-videos/entities/ref-video.entity.ts, src/ref-videos/entities/tag.entity.ts, src/ref-videos/ref-videos.controller.ts, src/ref-videos/ref-videos.service.ts
=> [#20] 학습용 동영상 조회 API에 tag 인자 적용

package-lock.json, package.json, src/app.module.ts, src/common/dtos/pagination.dto.ts, src/ref-videos/dtos/ref-videos.dto.ts, src/ref-videos/entities/ref-video.entity.ts, src/ref-videos/entities/tag.entity.ts, src/ref-videos/ref-videos.controller.ts, src/ref-videos/ref-videos.service.ts, src/tags/dtos/tags.dto.ts, src/tags/entities/tag.entity.ts, src/tags/tags.controller.ts, src/tags/tags.module.ts, src/tags/tags.service.ts
=> [#22] Tag API 개발

package-lock.json, package.json, src/common/dtos/pagination.dto.ts, src/ref-videos/dtos/ref-videos.dto.ts, src/ref-videos/dtos/search-ref-videos.dto.ts, src/ref-videos/entities/ref-video.entity.ts, src/ref-videos/entities/tag.entity.ts, src/ref-videos/ref-videos.controller.ts, src/ref-videos/ref-videos.service.ts
=> [#25] 학습용 동영상 검색 API 추가

src/members/entities/mbr-exp-history.entity.ts
복수형을 한쪽만 수정하고 다른 쪽을 수정안했더라구요...
#3
=> [#3] MemberExpHistory 칼럼 복수형 오타 수정

src/bookmarks/bookmarks.controller.ts, src/bookmarks/dtos/bookmarks.dto.ts, src/bookmarks/dtos/create-bookmark.dto.ts, src/bookmarks/dtos/delete-bookmark.dto.ts, src/common/dtos/output.dto.ts, src/common/dtos/pagination.dto.ts, src/common/entities/code.entity.ts, src/common/entities/core.entity.ts, src/practices/dtos/create-practice.dto.ts, src/practices/dtos/practices-today-sum.dto.ts, src/practices/entities/practice.entity.ts, src/practices/practices.controller.ts, src/ref-videos/dtos/ref-video.dto.ts, src/ref-videos/dtos/ref-videos.dto.ts, src/ref-videos/dtos/search-ref-videos.dto.ts, src/ref-videos/entities/ref-video.entity.ts, src/ref-videos/ref-videos.controller.ts, src/tags/dtos/tags.dto.ts, src/tags/entities/tag.entity.ts, src/tags/tags.controller.ts
=> [#14] 학습용 동영상, 보관, 연습 API에 Swagger 적용 

src/bookmarks/bookmarks.service.ts, src/common/dtos/pagination.dto.ts, src/members/entities/members.entity.ts, src/ref-videos/entities/ref-video.entity.ts, src/ref-videos/ref-videos.controller.ts, src/ref-videos/ref-videos.service.ts
=> [#31] 학습용 동영상 API 리팩토링

src/auth/auth-jwt.decorator.ts, src/auth/auth-jwt.middleware.ts, src/auth/auth-member.decorator.ts, src/auth/auth.controller.ts, src/auth/auth.guard.ts, src/auth/auth.service.ts, src/members/entities/members.entity.ts
request body 대신 request header로 jwt, member 정보 전달
#42 #35 #38
=> [#42] AuthJwt가 requst body에서 일으키는 충돌 해결

src/bookmarks/bookmarks.controller.ts, src/bookmarks/bookmarks.service.ts, src/bookmarks/dtos/create-bookmark.dto.ts, src/bookmarks/dtos/delete-bookmark.dto.ts, src/common/dtos/pagination.dto.ts, src/common/enums/code.enum.ts, src/members/entities/members.entity.ts, src/practices/dtos/create-practice.dto.ts, src/practices/entities/practice.entity.ts, src/practices/practices.controller.ts, src/practices/practices.service.ts, src/ref-videos/ref-videos.controller.ts, src/ref-videos/ref-videos.service.ts
=> [#33] 보관 API 리팩토링

src/bookmarks/bookmarks.controller.ts, src/bookmarks/bookmarks.service.ts, src/bookmarks/dtos/create-bookmark.dto.ts, src/bookmarks/dtos/delete-bookmark.dto.ts, src/common/dtos/pagination.dto.ts, src/common/enums/code.enum.ts, src/main.ts, src/members/entities/members.entity.ts, src/practices/dtos/create-practice.dto.ts, src/practices/entities/practice.entity.ts, src/practices/practices.controller.ts, src/practices/practices.service.ts, src/ref-videos/ref-videos.controller.ts, src/ref-videos/ref-videos.service.ts
=> [#45] swagger 상에서 jwt 토큰 넣고 테스트 가능하게 하기

src/common/enums/code.enum.ts, src/members/dtos/create-mbr-exp-history.ts, src/members/dtos/get-mbr-exp-history.ts, src/members/entities/members.entity.ts, src/members/mbr-exp-histories.service.ts, src/members/members.controller.ts, src/members/members.module.ts
=> [#49] 회원 경험치 이력 API 개발

src/main.ts, src/members/dtos/create-mbr-exp-history.ts, src/members/dtos/get-mbr-exp-history.ts, src/members/dtos/get-member.dto.ts, src/members/dtos/get-statics.dto.ts, src/members/entities/mbr-exp-history.entity.ts, src/members/entities/members.entity.ts, src/members/members.controller.ts, src/members/members.service.ts
=> [#51] 회원 API Swagger 작성

src/analyses/analyses.controller.ts, src/analyses/dtos/create-analysis-result.dto.ts, src/analyses/dtos/get-analyses.dto.ts, src/analyses/dtos/search-analyses.dto.ts, src/analyses/entities/analyses.entity.ts, src/analyses/enum/analysis-search-orderby.enum.ts, src/common/dtos/pagination.dto.ts, src/main.ts
=> [#53] 분석 Swagger 작성

src/auth/auth-jwt.middleware.ts, src/auth/auth.controller.ts, src/auth/auth.guard.ts, src/auth/auth.service.ts, src/auth/dtos/get-kakak-login-url.dto.ts, src/auth/dtos/get-token.dto.ts, src/auth/dtos/kakao-redirect.dto.ts, src/main.ts, src/members/members.controller.ts, src/members/members.service.ts
=> [#52] 인증 Swagger 작성

src/bookmarks/bookmarks.service.ts
=> [#59] 북마크 등록이 안되는 버그 수정

src/bookmarks/bookmarks.controller.ts, src/bookmarks/bookmarks.service.ts, src/bookmarks/dtos/check-bookmark.dto.ts
=> [#62] 학습용 영상마다 북마크 여부 조회 API  구현

src/members/members.service.ts
- 회원 탈퇴시 mbrKakaoSeq 칼럼도 같이 삭제처리
#58
=> [#58] 회원 탈퇴 후 재가입시 발생하는 버그 수정

src/ref-videos/dtos/create-ref-video.dto.ts, src/ref-videos/entities/ref-video.entity.ts, src/ref-videos/ref-videos.controller.ts, src/ref-videos/ref-videos.service.ts
=> [#66] [#74] 학습용 영상 등록 API 구현

src/ref-videos/entities/ref-video.entity.ts
refVideo 의 rvDifficulty 속성을 rvDifficultyCd 로 네이밍 변경
#83
=> [#83] refVideo 의 rvDifficulty 속성을 rvDifficultyCd 로 네이밍 변경

src/analyses/analyses.service.ts, src/members/mbr-statics.service.ts
- 연습 결과에서만 선호하는 댄서를 집계하고 있어서 빈 값으로 나왔었음. -> 분석 결과에서도 같이 집계함으로서 해결
- 연습 시간도 연습 + 분석결과 시간을 모두 합치는 것으로 변경
- 분석 결과 목록 최신순 정렬함.
#101
=> [#101] 통계 오류 해결

src/analyses/analyses.service.ts
- 저번에 혜성님이 부탁하셔서 GET /analyses 요청시 duration을 불러오도록 했다.
- 분명 머지까지 제대로한 기억이 있는데 내가 깜박하고 안한건지, 아니면 충돌나서 해결하자가 날라간건지 사라졌다.
- 그래서 다시 머지해야한다.
#105 #101
=> [#105] analyses 칼럼 전부 가져오기

src/bookmarks/bookmarks.service.ts
이전에 보관한 학습용 영상을 불러오지 못해서 발생한 문제였음
현재는 이전에 보관한 학습용 영상을 불러와서 새로 업데이트 한다음 저장해주는 방식으로 수정
#107
=> [#107] 영상 보관시 이전에 보관한 영상이 보관해제되는 버그 수정
